version: 2.1
jobs:
  bobby:
    docker:
      - image: circleci/node:latest
       
    steps:
      - checkout
      - run: echo "this is the build job"

  sally:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Doouble trouble"
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally
     