version: 2.0
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
       
    steps:
      - checkout
      - run: echo "this is the build job"

  sally:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - run: echo "Doouble trouble"
workflows:
  version: 2.0
  bobby_sally:
    jobs:
      - bobby
      - sally
     