version: 2.0
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.1-node
       
    steps:
      - checkout
      - run: echo "this is the build job"
      - store_test_results:
          path: test-results